### ISSUE TITLE
Mysql Slave/Master fails on second rebuild if volume is set

### ISSUE THREAD

**Issue by DubFriend** [tutumcloud/mysql#80]
Hi, awesome Docker repo. This has made my mysql ops work much easier!

I have hit a bit of a snag when using the master/slave setup with volumes.

My problem is that the master container errors out with:
`ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'replica'@'%'`

The second time I build. Note that the problem goes away if I do not use a volume in my docker-compose.yml file.

**docker-compose.yml**
```yaml
mysql:
  build: ../../containers/mysql
  name: mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql:rw
  environment:
    - MYSQL_USER=admin
    - MYSQL_PASS=admin
    - REPLICATION_MASTER=true
  container_name: mysql
  restart: always

mysql_slave:
  build: ../../containers/mysql
  links:
    - mysql
  ports:
    - "3307:3306"
  environment:
    - MYSQL_USER=admin
    - MYSQL_PASS=admin
    - REPLICATION_SLAVE=true
  container_name: mysql_slave
  restart: always
```

This works fine on the first boot.

`$ docker-compose build && docker-compose up -d`

but if i remove and rebuild it fails

`$ docker-compose stop && docker-compose rm && docker-compose build && docker-compose up -d`

I then get the error

`ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'replica'@'%'`

**tutumcloud/mysql/5.6/run.sh**
```bash
# Set MySQL REPLICATION - MASTER
if [ -n "${REPLICATION_MASTER}" ]; then
    echo "=> Configuring MySQL replication as master (2/2) ..."
    if [ ! -f /replication_set.2 ]; then
        echo "=> Creating a log user ${REPLICATION_USER}:${REPLICATION_PASS}"
        mysql -uroot -e "CREATE USER '${REPLICATION_USER}'@'%' IDENTIFIED BY '${REPLICATION_PASS}'"
        mysql -uroot -e "GRANT REPLICATION SLAVE ON *.* TO '${REPLICATION_USER}'@'%'"
        mysql -uroot -e "reset master"
        echo "=> Done!"
        touch /replication_set.2
    else
        echo "=> MySQL replication master already configured, skip"
    fi
fi
```

I am thinking that since a volume is set to preserve the database in my docker-compose file, but no volume is mounted for the flag file `touch /replication_set.2` above, that the user  "replica" is surviving rebuilds but the flag is not, thus causing this error.

Any help here is greatly appreciated.

Thank you :smiley:
